### ISSUE TITLE
Information about installing on Redmine 4.x

### ISSUE THREAD

**Issue by TitanFoxX** [tofi86/redmine_maintenance_mode#15]
While trying to migrate either of the plugins with the manuals provided, I get the following error in red, although Bundler v2.0.1 is installed :

> You must use Bundler 2 or greater with this lockfile.

Preventing these potential Bundler errors when installing either the Redmine_Base_Deface or Redmine_Maintenance_Mode plugins, I've made this small manual :

- Move into Redmine plugins directory
- `git clone https://github.com/jbbarth/redmine_base_deface`
- `chown -R apache:apache redmine_base_deface/`
- Move back into Redmine root directory
- `RAILS_ENV=production bundle exec rake redmine:plugins:migrate`
- Restart Redmine or reboot VM
</br>

- Move back into Redmine plugins directory
- `git clone https://github.com/tofi86/redmine_maintenance_mode.git`
- `chown -R apache:apache redmine_maintenance_mode`
- Move back into Redmine root directory
- `RAILS_ENV=production bundle exec rake redmine:plugins:migrate`
- Restart Redmine or reboot VM

**Comment by sphereweb83** [comment]
I get the following error.. did you also run into this?
```

bitnami@serv:/opt/bitnami/apps/redmine/htdocs$ rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for AccountController:Class
Did you mean?  alias_method
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_login_attempts_limit/lib/redmine_login_attempts_limit/account_controller_patch.rb:5:in `block in included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_login_attempts_limit/lib/redmine_login_attempts_limit/account_controller_patch.rb:4:in `class_eval'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_login_attempts_limit/lib/redmine_login_attempts_limit/account_controller_patch.rb:4:in `included'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_login_attempts_limit/init.rb:2:in `include'
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_login_attempts_limit/init.rb:2:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:181:in `block in load'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:172:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/redmine/plugin.rb:172:in `load'
/opt/bitnami/apps/redmine/htdocs/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:7:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

```

**Comment by saiballo** [comment]
hi,

any plan to migrate to 4.2?

**Comment by kroxy** [comment]
This method is deprecated. Please use Module#prepend that comes with [Ruby](https://apidock.com/ruby/RDoc/Parser/Ruby) 2.0 or newer instead.

[https://apidock.com/rails/Module/alias_method_chain](url)
